<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(WindowsTargetFramework)</TargetFramework>
    <TargetPlatformMinVersion>$(WindowsMinVersion)</TargetPlatformMinVersion>
    <RootNamespace>Hotshot.Capture</RootNamespace>
    <SupportedOSPlatformVersion>$(WindowsMinVersion)</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hotshot.Core\Hotshot.Core.csproj" />
  </ItemGroup>

</Project>
