<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(WindowsTargetFramework)</TargetFramework>
    <TargetPlatformMinVersion>$(WindowsMinVersion)</TargetPlatformMinVersion>
    <SupportedOSPlatformVersion>$(WindowsMinVersion)</SupportedOSPlatformVersion>
    <RootNamespace>Hotshot.Recording</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
    <PackageReference Include="Vortice.MediaFoundation" Version="3.8.3" />
    <PackageReference Include="NAudio.Core" Version="3.1.0" />
    <PackageReference Include="NAudio.Wasapi" Version="3.1.0" />
  </ItemGroup>

</Project>
