<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(WindowsTargetFramework)</TargetFramework>
    <TargetPlatformMinVersion>$(WindowsMinVersion)</TargetPlatformMinVersion>
    <SupportedOSPlatformVersion>$(WindowsMinVersion)</SupportedOSPlatformVersion>
    <RootNamespace>Hotshot.Gif</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.MediaFoundation" Version="3.8.3" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Hotshot.Gif.Tests" />
  </ItemGroup>

</Project>
